### ISSUE TITLE
Can I put the files separately in folders in the commands folder? please respond!

### ISSUE THREAD

**Issue by willCCodes** [BracketByte/DJS-Handler#1]
Hi! So I want to keep my commands folder neat so I thought if we could put the [command.name].js file in folders in the commands folder!

**Comment by BracketByte** [comment]
Hi there!  
The command handler loops through all the files and initializes them [here](https://github.com/BracketByte/DJS-Handler/blob/3f670988f2982631c0f3288da05f4aa6c6060e0c/handler/commandHandler.js#L8), if you add another loop inside so that it will loop through the folders then the files you will be able to make it work.
If you have any problems workkthing with the `fs` library I'll make the necessary changes for you

**Comment by willCCodes** [comment]
thanks! will be helpful.
